PORT = 5050
SERVER_IP = "172.22.240.1"
MESSAGE_SIZE = 2048

DISCONNECT_MESSAGE = "!DISONNECT"
UPDATE_HOST_MENU_MESSAGE = "!UPDATE_HOST_MENU"
UPDATE_GAME_MESSAGE = "!UPDATE_GAME"
CREATE_GAME_MESSAGE = "!CREATE_GAME"
LEAVE_MESSAGE = "!LEAVE"
JOIN_GAME_MESSAGE = "!JOIN_GAME"
START_GAME_MESSAGE = "!START_GAME"
FINISH_GAME_MESSAGE = "!FINISH_GAME"