FPS = 120

GAME_LOBBY_STATUS = "host lobby"
GAME_IN_PROGRESS_STATUS = "in progress"
GAME_STARTING_STATUS = "starting"
GAME_FINISHING_STATUS = "finishing"
GAME_PAUSED_STATUS = "paused"
LEAVE_GAME_STATUS = "leave"

PLAYER_SIZE = (42, 39)
PLAYER_HITBOX_FACTOR = 0.8
PLAYER_START_X = 80
PLAYER_START_Y = 80

PLAYER_ALIVE_STATUS = "alive"
PLAYER_DESTROYED_STATUS = "destroyed"

ACCELERATION = 0.1 * 60 / FPS
PASSIVE_SPEED_DECREASE_FACTOR = 0.02 * 60 / FPS
MAX_SPEED = 3.5 * 60 / FPS
MIN_SPEED = PASSIVE_SPEED_DECREASE_FACTOR
ROTATION_SPEED = 5 * 60 / FPS

GUN_OFFSET = 20
SHOOT_COOLDOWN = 80 * FPS / 60
BULLET_SIZE = (15, 15)
BULLET_SPEED = 10 * 60 / FPS
