PLAYER_SIZE = (42, 39)
PLAYER_HITBOX_FACTOR = 0.8
PLAYER_START_X = 80
PLAYER_START_Y = 80

ACCELERATION = 0.3
PASSIVE_SPEED_DECREASE_FACTOR = 0.02
MAX_SPEED = 3.5
MIN_SPEED = PASSIVE_SPEED_DECREASE_FACTOR
ROTATION_SPEED = 5

GUN_OFFSET = 20
SHOOT_COOLDOWN = 80
BULLET_SIZE = (15, 15)
BULLET_SPEED = 10
